site_name: ZmdC
#site_url: https://hpb-htw.github.io/zmdc-doc/

nav:
  - User Manual: index.md
  - Github: https://github.com/hpb-htw/zmdc
  - Coverage: https://hpb-htw.github.io/zmdc-doc/coverage

markdown_extensions:
  - toc # table of content
  - callouts # https://oprypin.github.io/markdown-callouts/index.html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "#"

theme:
  language: en
  name: material
  favicon: ./favicon.svg
  logo: ./favicon.svg
  features:
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
    - toc.integrate


extra_css:
  - lib/demo.css
  - static/extra.css
